const ACTION_TYPES = {
  CHANGE_THEME: 'CHANGE_THEME',

  // GET
  GET_BETS_ACTION: 'GET_BETS_ACTION',
  GET_BETS_REQUEST: 'GET_BETS_REQUEST',
  GET_BETS_SUCCESS: 'GET_BETS_SUCCESS',
  GET_BETS_ERROR: 'GET_BETS_ERROR',

  // CREATE
  CREATE_BET_ACTION: 'CREATE_BET_ACTION',
  CREATE_BET_REQUEST: 'CREATE_BET_REQUEST',
  CREATE_BET_SUCCESS: 'CREATE_BET_SUCCESS',
  CREATE_BET_ERROR: 'CREATE_BET_ERROR',

  // DELETE
  DELETE_BET_ACTION: 'DELETE_BET_ACTION',
  DELETE_BET_REQUEST: 'DELETE_BET_REQUEST',
  DELETE_BET_SUCCESS: 'DELETE_BET_SUCCESS',
  DELETE_BET_ERROR: 'DELETE_BET_ERROR',

  // UPDATE
  UPDATE_BET_ACTION: 'UPDATE_BET_ACTION',
  UPDATE_BET_REQUEST: 'UPDATE_BET_REQUEST',
  UPDATE_BET_SUCCESS: 'UPDATE_BET_SUCCESS',
  UPDATE_BET_ERROR: 'UPDATE_BET_ERROR'
};

export default ACTION_TYPES;
